### ISSUE TITLE
Link to GitHub repo in blog post

### ISSUE THREAD

**Issue by dbeatty10** [oresttokovenko/gpt-anki#1]
This is a cool project @oresttokovenko!

In [this](https://www.oresttokovenko.com/blog/anki-python) blog post, it says:
> You can find the prompt, and script that I used in my [Github repo here](https://www.oresttokovenko.com/blog/www.google.ca). To set up the environment, follow the instructions in the link.

But I'm guessing it should be this instead:
> You can find the prompt, and script that I used in my [GitHub repo here](https://www.oresttokovenko.com/blog/anki-python). To set up the environment, follow the instructions in the link.

**Comment by oresttokovenko** [comment]
@dbeatty10 Thank you very much! It's been updated
